### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/embedded-dma#22]
Now that #19 and #14 have been merged, it may make sense to make a new release.
@thalesfragoso do you want to rather wait to get something else in?

**Comment by andrewgazelka** [comment]
@eldruin @thalesfragoso any updates?

**Comment by thalesfragoso** [comment]
I think a release would be great, and I think #20 is non-breaking, right ? (I haven't found the time to review it yet).

**Comment by andrewgazelka** [comment]
> I think a release would be great, and I think #20 is non-breaking, right ? (I haven't found the time to review it yet).

Correct, it is non-breaking.
